### ISSUE TITLE
EditorConfig: remove `end_of_line` for Windows users

### ISSUE THREAD

**Issue by fahad19** [Travix-International/frint#285]
See previous discussion with @markvincze here: https://github.com/Travix-International/travix-appix-templates/pull/4#discussion_r118269044

Removing that line would help Windows users better.

**Comment by mAiNiNfEcTiOn** [comment]
@fahad19 can't see any benefit on it. Doesn't harm Windows users AFAIK. And last but not the least, for .md you can do an exception (as you mentioned on the pr referenced above)

**Comment by fahad19** [comment]
@discosultan, @markvincze: can you please explain the Git issue regarding this that you were mentioning before? thanks!

**Comment by discosultan** [comment]
@mAiNiNfEcTiOn valid point and this PR is flawed *on Windows*! I'll try to shed some light. When dealing with this issue, we need to take into account git, editor and linter (which I missed).

---

For default installation of Git for Windows, the `core.autocrlf` option is `true`. This means when checking in to remote, eol is set to `LF`  and when checking out, `CRLF`.

Having `LF` enforced in `.editorconfig` makes editors such as VS Code pick this up and use it on edited files, so you end up with a mix of files using `LF` and `CRLF`.

Linter, by default, is ensuring `LF` as eol. If git has converted `LF` to `CRLF`, the editor becomes bloody red! ([ref](https://eslint.org/docs/rules/linebreak-style))

---

One downside to forcing `LF` on windows is editors such as VS that likes to work with `CRLF`. I think that is no longer an issue with VS 2017 if `.editorconfig` is present specifying eol.

When using Bash on Windows, it's actually nice if the project is using `LF` as eol when sharing files between Windows & Ubuntu environments.

---

I'd propose to actually revert the PR and introduce a `.gitattributes` file which overrides global git settings in order to prevent `core.autocrlf=true` behavior for Windows users. Ideally we'd want to do `core.autorlf=input`. ([ref](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#__code_core_autocrlf_code))
