### ISSUE TITLE
Running tests on individual packages not working

### ISSUE THREAD

**Issue by fahad19** [Travix-International/frint#294]
Tried both:

```
$ (cd ./packages/frint-react/ && npm test)
```

and:

```
$ lerna run --scope frint-react test
```

It comes down to `cross-env` not being available during execution.

**Comment by fahad19** [comment]
PR #281 could be related.

**Comment by discosultan** [comment]
After removing relative paths from packages ([as seen here](https://github.com/Travix-International/frint/commit/6be4f173a02b50a6ea9319175ea3983809701434)), all the npm scripts work fine for me when using `lerna run --scope <package> <script>`. I tried with both working dir being root as well as the package folder. Obviously `npm run <script>` does no longer work, since the required deps are missing from the local package's `node_modules` folder.

I'm confused of the behavior of `lerna` and why scoped execution sometimes manages to find modules from root and sometimes doesn't ... Tested with `lerna` v2.2.0.

**Comment by fahad19** [comment]
I am cool, as long as I can run them them individually while developing.

**Comment by fahad19** [comment]
Does installing `cross-env` for every package help? not preferred, but looking into reliable options here.

**Comment by discosultan** [comment]
> Does installing cross-env for every package help? not preferred, but looking into reliable options here.

That would be a solution and this package (together with all its deps) is relatively small (~80KB with metadata, ~30KB source only).

-----

I still need to figure out the case where dep is missing from local package but present in root, when does `lerna run --scoped ...` work and when not. Knowing this, we may find a much better solution than including `cross-env` everywhere.

**Comment by discosultan** [comment]
Tested both on Windows and Ubuntu without issues. I know there's a problem somewhere (maybe related to tooling versioning) but am unable to reproduce.

@fahad19 Can you try scoped execution on this branch?

**Comment by fahad19** [comment]
Running `lerna run --scope frint-react test` worked for me in this branch.

One problem I see when tests are expected to fail: the `lerna run` will print the npm output a few times in the Terminal: https://github.com/lerna/lerna/issues/592
